// Represents the core domain entity for a product in the system.
// This is the data model that maps directly to the database table via EF Core.
namespace MyApi.Models;

public class Product
{
    // Unique identifier for the product (auto-generated by the database).
    public int Id { get; set; }

    // Display name of the product.
    public string Name { get; set; } = string.Empty;

    // Monetary value of the product stored as decimal for precision.
    public decimal Price { get; set; }

    // Soft-delete / visibility flag. Only active products are returned by queries.
    // Defaults to true when a new product is created.
    public bool IsActive { get; set; } = true;
}
